version: '3.8'

services:
  master:
    image: postgres:latest
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./master-init.sh:/docker-entrypoint-initdb.d/master-init.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnet_ext

  slave1:
    image: postgres:latest
    container_name: postgres-slave1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    depends_on:
      - master
    ports:
      - "15432:5432"
    volumes:
      - slave1_data:/var/lib/postgresql/data
      - ./slave-init.sh:/docker-entrypoint-initdb.d/slave-init.sh
    command: "postgres -c synchronous_standby_names='*'"
    networks:
      - pgnet_ext

  slave2:
    image: postgres:latest
    container_name: postgres-slave2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    depends_on:
      - master
    ports:
      - "25432:5432"
    volumes:
      - slave2_data:/var/lib/postgresql/data
      - ./slave-init.sh:/docker-entrypoint-initdb.d/slave-init.sh
    command: "postgres -c synchronous_standby_names='*'"
    networks:
      - pgnet_ext

volumes:
 master_data:
 slave1_data:
 slave2_data:

networks:
  pgnet_ext:
    name: pgnet
    external: true