version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      REPLICATION_USER: repl_user
      REPLICATION_PASSWORD: repl_password
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./master_setup.sh:/docker-entrypoint-initdb.d/master_setup.sh
    networks:
      - pgnet_ext
    labels:
      - "role=master"

  db_slave1:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      REPLICATION_USER: repl_user
      REPLICATION_PASSWORD: repl_password
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    depends_on:
      - db
    networks:
      - pgnet_ext
    volumes:
      - ./slave1_data:/var/lib/postgresql/data
      - ./pgpass:/var/lib/postgresql/.pgpass
    command: >
      sh -c '
        until pg_isready -h db -U postgres; do
          echo "Waiting for master to be ready...";
          sleep 1;
        done;
        echo "Master is ready. Starting base backup...";
        PGPASSWORD=repl_password pg_basebackup -h db -D /var/lib/postgresql/data -U repl_user -vP -R;
        echo "Base backup completed. Setting correct ownership and permissions...";
        chown -R postgres:postgres /var/lib/postgresql/data;
        chmod 700 /var/lib/postgresql/data;
        exec gosu postgres postgres'
    labels:
      - "role=slave"

  db_slave2:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      REPLICATION_USER: repl_user
      REPLICATION_PASSWORD: repl_password
      POSTGRES_DB: postgres
    ports:
      - "5437:5432"
    depends_on:
      - db
    networks:
      - pgnet_ext
    volumes:
      - ./slave2_data:/var/lib/postgresql/data
      - ./pgpass:/var/lib/postgresql/.pgpass
    command: >
      sh -c '
        until pg_isready -h db -U postgres; do
          echo "Waiting for master to be ready...";
          sleep 1;
        done;
        echo "Master is ready. Starting base backup...";
        PGPASSWORD=repl_password pg_basebackup -h db -D /var/lib/postgresql/data -U repl_user -vP -R;
        echo "Base backup completed. Setting correct ownership and permissions...";
        chown -R postgres:postgres /var/lib/postgresql/data;
        chmod 700 /var/lib/postgresql/data;
        exec gosu postgres postgres'
    labels:
      - "role=slave"

  haproxy:
    image: haproxy:latest
    depends_on:
      - db
      - db_slave1
      - db_slave2
    ports:
      - "5435:5432"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - pgnet_ext

networks:
  pgnet_ext:
    name: pgnet
    external: true