version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnet_ext

networks:
  pgnet_ext:
    name: pgnet
    external: true