CREATE TABLE public.users (
    id VARCHAR(255),
    first_name VARCHAR(255),
    second_name VARCHAR(255),
    birthdate DATE,
    sex VARCHAR(255),
    biography TEXT,
    city VARCHAR(255),
    username VARCHAR(255) NOT NULL,
    password BYTEA NOT NULL
);

CREATE TABLE public.subscribers (
	id VARCHAR(255) not NULL,
    user_id VARCHAR(255) not NULL
);

CREATE TABLE public.posts (
	id SERIAL primary KEY,
    user_id VARCHAR(255) not NULL,
    content text not NULL,
    post_date TIMESTAMP NOT NULL
);

CREATE TABLE public.tokens (
	user_id VARCHAR(255) not NULL,
    token VARCHAR(255) not NULL,
    created_at TIMESTAMP NOT NULL
);


CREATE ROLE repl_user WITH REPLICATION LOGIN PASSWORD 'repl_password';


-- create extension if not exists "uuid-ossp"

-- INSERT INTO public.users
-- (id,first_name, second_name, birthdate, sex, biography, city, username, password)
-- select
-- 	uuid_generate_v4()::TEXT,
-- 	first_names[ceil(random()*array_length(first_names,1))],
-- 	second_names[ceil(random()*array_length(second_names,1))],
-- 	timestamp '1990-01-01',
-- 	'-',
-- 	'qqq',
-- 	city[ceil(random()*array_length(city,1))],
-- 	first_names[ceil(random()*array_length(first_names,1))] || random()::TEXT,
-- 	'123456' 
-- from
-- 	generate_series(1,1000000) as g(n),
-- 	(values (array['Hazel',
-- 					'Janice',
-- 					'Laura',
-- 					'Jessica',
-- 					'Jose',
-- 					'Erika',
-- 					'Tanya',
-- 					'Terry',
-- 					'Susan',
-- 					'Randall',
-- 					'Helen',
-- 					'Kim',
-- 					'Daniel',
-- 					'Kirk',
-- 					'Sherry',
-- 					'Christopher',
-- 					'Wade',
-- 					'Ruby',
-- 					'Amy',
-- 					'Joseph',
-- 					'Agnes',
-- 					'Herbert',
-- 					'Roy',
-- 					'Matthew',
-- 					'Tony',
-- 					'Clara',
-- 					'Jeffery',
-- 					'Keith',
-- 					'Jack',
-- 					'Zachary',
-- 					'Cheryl',
-- 					'Troy',
-- 					'Harry',
-- 					'Irene',
-- 					'Sylvia',
-- 					'Elizabeth',
-- 					'Melanie',
-- 					'Frank',
-- 					'Michael',
-- 					'Christine',
-- 					'Jeffrey',
-- 					'Charlie',
-- 					'Alice',
-- 					'Jacqueline',
-- 					'Timothy',
-- 					'Lillian',
-- 					'Anne',
-- 					'Peter',
-- 					'Nicole',
-- 					'James',
-- 					'Linda',
-- 					'Jerome',
-- 					'Jacob',
-- 					'Donald',
-- 					'Crystal',
-- 					'Samantha',
-- 					'Pamela',
-- 					'David',
-- 					'Joel',
-- 					'Robert',
-- 					'Donna',
-- 					'Tommy',
-- 					'Sharon',
-- 					'Shirley',
-- 					'Lawrence',
-- 					'Doris',
-- 					'Alvin',
-- 					'Lois',
-- 					'Dennis',
-- 					'Joe',
-- 					'Jill',
-- 					'Ernest',
-- 					'Kathleen',
-- 					'Lynn',
-- 					'Carol',
-- 					'William',
-- 					'Alexander',
-- 					'Henry',
-- 					'Barbara',
-- 					'Derek',
-- 					'Karen'
-- 					]))
-- 			as first_names(first_names),
-- 	(values (array['Armstrong',
-- 					'Bell',
-- 					'Green',
-- 					'Young',
-- 					'Hamilton',
-- 					'Hansen',
-- 					'Sharp',
-- 					'Allen',
-- 					'Jackson',
-- 					'Marsh',
-- 					'Williams',
-- 					'Mitchell',
-- 					'Terry',
-- 					'McCormick',
-- 					'Collins',
-- 					'Smith',
-- 					'Palmer',
-- 					'Davis',
-- 					'Webster',
-- 					'Alexander',
-- 					'West',
-- 					'Garcia',
-- 					'Parker',
-- 					'Neal',
-- 					'Lewis',
-- 					'Murphy',
-- 					'Shaw',
-- 					'Flores',
-- 					'Morgan',
-- 					'Willis',
-- 					'Cox',
-- 					'Santiago',
-- 					'Conner',
-- 					'Perkins',
-- 					'Johnson',
-- 					'Anderson',
-- 					'Cortez',
-- 					'Rose',
-- 					'Underwood',
-- 					'Cross',
-- 					'Quinn',
-- 					'Reyes',
-- 					'Hines',
-- 					'Higgins',
-- 					'Myers',
-- 					'Bryant',
-- 					'Bennett',
-- 					'Hawkins',
-- 					'Hall',
-- 					'Jenkins',
-- 					'Knight',
-- 					'Morris',
-- 					'Roberts',
-- 					'Sanchez',
-- 					'Houston',
-- 					'Oliver',
-- 					'Stewart',
-- 					'Webb',
-- 					'Welch',
-- 					'McLaughlin',
-- 					'Ramirez',
-- 					'Taylor',
-- 					'Harrison',
-- 					'Kelly',
-- 					'Moore',
-- 					'Rodriguez',
-- 					'Watkins',
-- 					'Brown',
-- 					'Phillips',
-- 					'Hill',
-- 					'Harvey',
-- 					'Thompson',
-- 					'Bass',
-- 					'Dixon',
-- 					'Tate',
-- 					'Martin',
-- 					'Miller',
-- 					'Ortiz',
-- 					'Cobb',
-- 					'Peterson',
-- 					'Fuller',
-- 					'Harris',
-- 					'Kennedy',
-- 					'Carter',
-- 					'Chambers'
-- 					]))
-- 			as second_names(second_names),
-- 			(values (array['austin','tulsa','houston','athens','mission','salina','chapton','waco','kadoka','nashville']))
-- 			as city(city)	
