services:
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - zabbix_db_data:/var/lib/mysql
      - ./zabbix-schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - pgnet_ext

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.4.0
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - pgnet_ext

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4.0
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: UTC
    depends_on:
      - zabbix-server
      - zabbix-db
    ports:
      - "8083:8080"
    networks:
      - pgnet_ext

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - pgnet_ext
    depends_on:
      - zabbix-server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - pgnet_ext
    depends_on:
      - prometheus
      - zabbix-server

volumes:
  zabbix_db_data:
  zabbix_server_data:
  grafana_data:

networks:
  pgnet_ext:
    name: pgnet
    external: true